// Mapeamento de código IATA -> nome da cidade (usado para buscar foto do destino)
// Cidades com nomes ambíguos na Wikipedia recebem um qualificador entre parênteses.
export const IATA_CITIES: Record<string, string> = {
  // Brasil
  GRU: "São Paulo", CGH: "São Paulo", VCP: "Campinas",
  GIG: "Rio de Janeiro", SDU: "Rio de Janeiro",
  CNF: "Belo Horizonte", PLU: "Belo Horizonte",
  BSB: "Brasília",
  SSA: "Salvador (Bahia)",
  REC: "Recife",
  FOR: "Fortaleza",
  POA: "Porto Alegre",
  CWB: "Curitiba",
  FLN: "Florianópolis",
  VIX: "Vitória (Espírito Santo)",
  NAT: "Natal (Rio Grande do Norte)",
  MCZ: "Maceió",
  AJU: "Aracaju",
  JPA: "João Pessoa",
  THE: "Teresina",
  SLZ: "São Luís",
  BEL: "Belém",
  MAO: "Manaus",
  PVH: "Porto Velho",
  RBR: "Rio Branco",
  BVB: "Boa Vista",
  MCP: "Macapá",
  PMW: "Palmas",
  CGB: "Cuiabá",
  CGR: "Campo Grande",
  GYN: "Goiânia",
  UDI: "Uberlândia",
  IGU: "Foz do Iguaçu",
  LDB: "Londrina",
  MGF: "Maringá",
  JOI: "Joinville",
  NVT: "Navegantes",
  IOS: "Ilhéus",
  PNZ: "Petrolina",
  IMP: "Imperatriz",
  STM: "Santarém",
  OPS: "Sinop",
  JDO: "Juazeiro do Norte",
  CXJ: "Caxias do Sul",
  PET: "Pelotas",
  UBA: "Uberaba",
  RAO: "Ribeirão Preto",
  SJP: "São José do Rio Preto",
  BAU: "Bauru",
  PPB: "Presidente Prudente",
  ARU: "Araçatuba",

  // Internacional
  MVD: "Montevidéu",
  EZE: "Buenos Aires", AEP: "Buenos Aires",
  SCL: "Santiago do Chile",
  LIM: "Lima",
  BOG: "Bogotá",
  UIO: "Quito",
  ASU: "Assunção",
  LPB: "La Paz",
  LIS: "Lisboa",
  OPO: "Porto",
  MAD: "Madrid",
  BCN: "Barcelona",
  CDG: "Paris", ORY: "Paris",
  LHR: "Londres", LGW: "Londres",
  FCO: "Roma",
  MXP: "Milão",
  FRA: "Frankfurt",
  AMS: "Amsterdã",
  MIA: "Miami",
  MCO: "Orlando",
  JFK: "Nova York", EWR: "Nova York", LGA: "Nova York",
  LAX: "Los Angeles",
  IAD: "Washington",
  ATL: "Atlanta",
  CUN: "Cancún",
  PUJ: "Punta Cana",
  PTY: "Cidade do Panamá",
  MEX: "Cidade do México",
  DXB: "Dubai",
  IST: "Istambul",
};
